100 numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100

1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [11]:
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/Users/deviniverson/opt/anaconda3/lib/python3.6/site-packages/numpy/version.py'>
<function show at 0x109c94d90>


3. Create a null vector of size 10 (★☆☆)
​

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)


In [19]:
a = np.array((4,4))
print(a.size, a.itemsize)

2 8


5. How to get the documentation of the numpy add function from the command line? (★☆☆)
​

In [ ]:
"help function"

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
​

In [25]:
n = np.zeros(10)
n[5]=1
print(n)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)
​

In [29]:
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)
​

In [30]:
n = np.arange(1, 100)
n[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
​

In [35]:
n = np.arange(9).reshape(3,3)
print(n)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
​

In [38]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix (★☆☆)
​

In [41]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)
​

In [46]:
import random
r = np.random.random((3,3,3))
print(r)

[[[0.32571569 0.01002337 0.73616861]
  [0.25726126 0.87627348 0.40913762]
  [0.28685485 0.61239735 0.39032214]]

 [[0.43458771 0.82703701 0.99475915]
  [0.10490564 0.16255957 0.51553161]
  [0.02814092 0.17263334 0.5244479 ]]

 [[0.99496836 0.92369123 0.51806606]
  [0.55928036 0.04187548 0.06589576]
  [0.0292371  0.78392354 0.9554688 ]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
​

In [52]:
a = np.random.random((10,10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.002685020740516686 0.9970880123019091


14. Create a random vector of size 30 and find the mean value (★☆☆)
​

In [56]:
a = np.random.random(30)
mean = a.mean()
print(mean)

0.511167308970211


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
​

In [57]:
z = np.ones((10,10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)
​

In [60]:
p = np.pad(z, pad_width=1, mode='constant')
print(p)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)

In [68]:
0 * np.nan

nan

In [67]:
np.nan == np.nan

False

In [66]:
np.inf > np.nan

False

In [65]:
np.nan - np.nan

nan

In [64]:
np.nan in set([np.nan])

True

In [63]:
0.3 == 3 * 0.1

False

In [61]:
''' 0 * np.nan 'nan' 
np.nan == np.nan 'False'
np.inf > np.nan 
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

'''

nan

In [62]:
np.nan == np.nan

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
​

In [76]:
z = np.diag(1+np.arange(5), k=-1)
print(z)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
​

In [83]:
z = np.zeros((8, 8), dtype=int)
z[1::2,::2] = 1
z[::2, 1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
​

In [87]:
z = np.unravel_index(99,(6,7,8))
print(z)

(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
​

In [90]:
z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix (★☆☆)
​

In [95]:
z = np.random.random((5, 5))
z = (1 - np.mean(z)) / (np.std(z))
print(z)

1.5648653716233065


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
​

In [96]:
color = np.dtype([("r", np.ubyte, 1), 
                  ("g", np.ubyte, 1), 
                  ("b", np.ubyte, 1), 
                  ("y", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('y', 'u1')]


/Users/deviniverson/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
​

In [101]:
z = np.ones((5,3))@np.ones((3,2))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
​

In [113]:
z = np.arange(11)
z[(3 < z) & (z <= 8)] *=-1
print()
print(z)

[ 0. +0.j  0. +1.j  0. +2.j  0. +3.j -0. -4.j -0. -5.j -0. -6.j -0. -7.j
 -0. -8.j  0. +9.j  0.+10.j]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

In [108]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [116]:
Z = np.arange(11)
Z**Z 

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [115]:
2 << Z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [117]:
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [118]:
1j*Z

array([0. +0.j, 0. +1.j, 0. +2.j, 0. +3.j, 0. +4.j, 0. +5.j, 0. +6.j,
       0. +7.j, 0. +8.j, 0. +9.j, 0.+10.j])

In [119]:
Z/1/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
Z<Z>Z
Does not work, more than one element is ambibuous

28. What are the result of the following expressions?

In [121]:
np.array(0) / np.array(0)

/Users/deviniverson/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [122]:
np.array(0) // np.array(0)

/Users/deviniverson/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [123]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

29. How to round away from zero a float array ? (★☆☆)
​

In [124]:
z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(z)), z))

[-3.  3. -5.  7.  7.  5. -6.  6. -9. -2.]


30. How to find common values between two arrays? (★☆☆)
​

In [126]:
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)
print(z1)
print(z2)
print(np.intersect1d(z1, z2))

[5 7 2 2 7 3 1 5 5 6]
[4 3 8 4 8 7 9 0 3 0]
[3 7]


31. How to ignore all numpy warnings (not recommended)? (★☆☆)
​

32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)
​

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
​

34. How to get all the dates corresponding to the month of July 2016? (★★☆)
​

35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
​

36. Extract the integer part of a random array using 5 different methods (★★☆)
​

37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
​

38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
​

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
​

40. Create a random vector of size 10 and sort it (★★☆)
​

41. How to sum a small array faster than np.sum? (★★☆)
​

42. Consider two random array A and B, check if they are equal (★★☆)
​

43. Make an array immutable (read-only) (★★☆)
​

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
​

45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
​

46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
​

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
​

48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
​

49. How to print all the values of an array? (★★☆)
​

50. How to find the closest value (to a given scalar) in a vector? (★★☆)
​

51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
​

52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
​

53. How to convert a float (32 bits) array into an integer (32 bits) in place?
​

54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
​

55. What is the equivalent of enumerate for numpy arrays? (★★☆)
​

56. Generate a generic 2D Gaussian-like array (★★☆)
​

57. How to randomly place p elements in a 2D array? (★★☆)
​

58. Subtract the mean of each row of a matrix (★★☆)
​

59. How to sort an array by the nth column? (★★☆)
​

60. How to tell if a given 2D array has null columns? (★★☆)
​

61. Find the nearest value from a given value in an array (★★☆)
​

62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
​

63. Create an array class that has a name attribute (★★☆)
​

64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
​

65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
​

66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
​

67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
​

68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
​

69. How to get the diagonal of a dot product? (★★★)
​

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
​

71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
​

72. How to swap two rows of an array? (★★★)
​

73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)
​

74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
​

75. How to compute averages using a sliding window over an array? (★★★)
​

76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
​

77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
​

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
​

79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
​

80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
​

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
​

82. Compute a matrix rank (★★★)
​

83. How to find the most frequent value in an array?
​

84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
​

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
​

86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
​

87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
​

88. How to implement the Game of Life using numpy arrays? (★★★)
​

89. How to get the n largest values of an array (★★★)
​

90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
​

91. How to create a record array from a regular array? (★★★)
​

92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
​

93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
​

94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
​

95. Convert a vector of ints into a matrix binary representation (★★★)
​

96. Given a two dimensional array, how to extract unique rows? (★★★)
​

97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
​

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
​

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
​

100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
​